# -*- coding: utf-8 -*-
"""Generative Ai(text to image).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QJmFs2CQaFtb7TmLhsaGyYqxBcJae4g
"""

! pip install diffusers transformers accelerate safetensors

from diffusers import StableDiffusionPipeline
import torch
import matplotlib.pyplot as plt

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device", device)

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype = torch.float16
)

pipe = pipe.to(device)

# Text prompt
prompt = "A futuristic product advertisement of a smartwatch with neon lights, ultra realistic, high quality"

# Generate image
image = pipe(prompt).images[0]

# Show image
plt.imshow(image)
plt.axis("off")
plt.show()

# Save image
image.save("product_ad.png")

image = pipe(
    prompt,
    negative_prompt = "blurry,low quality,distorted"
).images[0]

plt.imshow(image)
plt.axis("off")
plt.show()

!pip install gradio

import gradio as gr

def generate_image(prompt):
    image = pipe(prompt).images[0]
    return image

# Launch Gradio app
demo = gr.Interface(
    fn=generate_image,
    inputs="text",
    outputs="image",
    title="Text-to-Image Generator",
    description="Enter any text and get a generated image using Stable Diffusion"
)

demo.launch()